import math

N_MELS = 128

SAMPLE_RATE = 16000
FRAMES_PER_SEC = 62.5
WINDOW_SIZE = 2048
HOP_SIZE = 256

PAD_MODE = "reflect"
WINDOW = "hann"
CHANNELS_NUM = 1
SHIFT_PITCH = 3

NOTES_NUM_EXCLUDE_SILENCE = 128
NOTES_NUM = NOTES_NUM_EXCLUDE_SILENCE + 1
F0_RES = 7
ONSET_RES = 3
F0S_NUM = NOTES_NUM_EXCLUDE_SILENCE * F0_RES
BEGIN_NOTE = 0
N_FFT = WINDOW_SIZE

BLOCK_SIZE = HOP_SIZE

