from conf.feature import *

SAMPLE_RES = 100
MAX_SOURCES_NUM = 5
DURATION = 2.56
SAMPLE_DURATION = int(SAMPLE_RATE * DURATION)
FRAME_DURATION = int(FRAMES_PER_SEC * DURATION)

TEST_BATCH_SIZE = 1
TRAINING_BATCH_SIZE = 16
SAMPLES_NUM = 6240 * 4

